//
//  MovieDetailsSceneInteractor.swift
//  Movie
//
//  Created by Gautam Singh on 3/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsSceneBusinessLogic
{
  func doSomething(request: MovieDetailsScene.Something.Request)
}

protocol MovieDetailsSceneDataStore
{
  //var name: String { get set }
}

class MovieDetailsSceneInteractor: MovieDetailsSceneBusinessLogic, MovieDetailsSceneDataStore
{
  var presenter: MovieDetailsScenePresentationLogic?
  var worker: MovieDetailsSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MovieDetailsScene.Something.Request)
  {
    worker = MovieDetailsSceneWorker()
    worker?.doSomeWork()
    
    let response = MovieDetailsScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
