//
//  MovieDetailsScenePresenter.swift
//  Movie
//
//  Created by Gautam Singh on 3/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsScenePresentationLogic
{
  func presentSomething(response: MovieDetailsScene.Something.Response)
}

class MovieDetailsScenePresenter: MovieDetailsScenePresentationLogic
{
  weak var viewController: MovieDetailsSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MovieDetailsScene.Something.Response)
  {
    let viewModel = MovieDetailsScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
